# Generated by Django 2.1.5 on 2019-01-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsocapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='userpostlikes',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
